version: '3'
services:
#mssql docker
  ecarservice-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - ecarservicenet

  ecarservice-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ecarservice-sql,1433;Database=IB190087;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5045:5045
    networks:
      - ecarservicenet
    links:
      - ecarservice-sql
    depends_on:
      - ecarservice-sql
      
networks:
  ecarservicenet:
    driver: bridge      